chore: testing MED-003

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -3,12 +3,6 @@
 
 echo 'Running pre-commit hook...'
 
-## Check for uncommitted changes
-yarn check-lint || (
-    echo 'TypeScript lint check failed.'
-    exit 1
-)
-
 ## Check tsconfing standards
 yarn check-types || (
     echo 'TypeScript check failed.'
@@ -17,11 +11,17 @@ yarn check-types || (
 
 ## Checking formatting
 yarn check-format || (
-    echo 'TypeScript formatting check failed.'
+    echo 'Prettier formatting check failed.'
     exit 1
 )
 
 yarn build || (
     echo 'Build failed.'
+    exit 1
+)
+
+## Check for uncommitted changes
+yarn check-lint || (
+    echo 'TypeScript lint check failed.'
     exit 1
 )
