fix: added yarn build in pre-commit MED-002

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -20,3 +20,8 @@ yarn check-format || (
     echo 'TypeScript formatting check failed.'
     exit 1
 )
+
+yarn build || (
+    echo 'Build failed.'
+    exit 1
+)
